// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.12.0
// source: Users/AUSA/Documents/IdeaProject/tgf-example/kit/proto/ws.proto

package rpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type WSMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Module      string `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	ServiceName string `protobuf:"bytes,2,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	Data        []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	ReqId       int32  `protobuf:"varint,4,opt,name=reqId,proto3" json:"reqId,omitempty"`
}

func (x *WSMessage) Reset() {
	*x = WSMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WSMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSMessage) ProtoMessage() {}

func (x *WSMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSMessage.ProtoReflect.Descriptor instead.
func (*WSMessage) Descriptor() ([]byte, []int) {
	return file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_rawDescGZIP(), []int{0}
}

func (x *WSMessage) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *WSMessage) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *WSMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WSMessage) GetReqId() int32 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

type WSResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType string `protobuf:"bytes,1,opt,name=messageType,proto3" json:"messageType,omitempty"`
	Data        []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ReqId       int32  `protobuf:"varint,3,opt,name=reqId,proto3" json:"reqId,omitempty"`
	Code        int32  `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *WSResponse) Reset() {
	*x = WSResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSResponse) ProtoMessage() {}

func (x *WSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSResponse.ProtoReflect.Descriptor instead.
func (*WSResponse) Descriptor() ([]byte, []int) {
	return file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_rawDescGZIP(), []int{1}
}

func (x *WSResponse) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *WSResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WSResponse) GetReqId() int32 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

func (x *WSResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto protoreflect.FileDescriptor

var file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_rawDesc = []byte{
	0x0a, 0x3f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x41, 0x55, 0x53, 0x41, 0x2f, 0x44, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x49, 0x64, 0x65, 0x61, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x2f, 0x74, 0x67, 0x66, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x6b,
	0x69, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x6f, 0x0a, 0x09, 0x57, 0x53, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x65, 0x71, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x65, 0x71,
	0x49, 0x64, 0x22, 0x6c, 0x0a, 0x0a, 0x57, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_rawDescOnce sync.Once
	file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_rawDescData = file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_rawDesc
)

func file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_rawDescGZIP() []byte {
	file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_rawDescOnce.Do(func() {
		file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_rawDescData = protoimpl.X.CompressGZIP(file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_rawDescData)
	})
	return file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_rawDescData
}

var file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_goTypes = []interface{}{
	(*WSMessage)(nil),  // 0: WSMessage
	(*WSResponse)(nil), // 1: WSResponse
}
var file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_init() }
func file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_init() {
	if File_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WSMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WSResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_goTypes,
		DependencyIndexes: file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_depIdxs,
		MessageInfos:      file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_msgTypes,
	}.Build()
	File_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto = out.File
	file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_rawDesc = nil
	file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_goTypes = nil
	file_Users_AUSA_Documents_IdeaProject_tgf_example_kit_proto_ws_proto_depIdxs = nil
}
