FROM golang:1.26-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ARG MAIN_PKG={{.MainPackage}}
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /out/app ${MAIN_PKG}

FROM alpine:3.21
WORKDIR /app
COPY --from=build /out/app /app/app
ENTRYPOINT ["/app/app"]
